# Generated by Django 3.0 on 2021-04-12 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account_channel_emails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='capital_investments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=250, null=True)),
                ('title', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='countrys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=250, null=True)),
                ('title', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='districts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=250, null=True)),
                ('title', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=250, null=True)),
                ('title', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='fields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=250, null=True)),
                ('title', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='level_accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=250, null=True)),
                ('title', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='phone_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=250, null=True)),
                ('title', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='potentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=250, null=True)),
                ('title', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='provinces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=250, null=True)),
                ('title', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='type_company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('personal', 'Cá nhân'), ('enterprise', 'Doanh nghiệp')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='wards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=250, null=True)),
                ('title', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('en_name', models.CharField(blank=True, max_length=250)),
                ('tax_code', models.CharField(blank=True, max_length=100)),
                ('representer', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_date_start', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_date_close', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('website', models.CharField(blank=True, max_length=250, null=True)),
                ('email_provider', models.CharField(blank=True, max_length=250, null=True)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('number_of_pc', models.IntegerField(blank=True, null=True)),
                ('number_of_server', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField(null=True)),
                ('supporter_id', models.IntegerField(null=True)),
                ('contacts', models.CharField(blank=True, max_length=250, null=True)),
                ('fields', models.CharField(blank=True, max_length=250, null=True)),
                ('emails', models.CharField(blank=True, max_length=150, null=True)),
                ('phones', models.CharField(blank=True, max_length=150, null=True)),
                ('is_del', models.IntegerField(default=0)),
                ('created_date', models.IntegerField(default=1618200151)),
                ('update_date', models.IntegerField(default=1618200151)),
                ('country', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.countrys')),
                ('district', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.districts')),
                ('employee', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.employees')),
                ('investment', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.capital_investments')),
                ('level', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.level_accounts')),
                ('potential', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.potentials')),
                ('province', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.provinces')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.type_company')),
                ('ward', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.wards')),
            ],
        ),
        migrations.CreateModel(
            name='account_channel_phones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=250, null=True)),
                ('phone_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.phone_type')),
            ],
        ),
    ]
