# Generated by Django 2.2.8 on 2021-04-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210415_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='created_date',
            field=models.IntegerField(default=1618456461),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='update_date',
            field=models.IntegerField(default=1618456461),
        ),
    ]
