# Generated by Django 2.2 on 2021-04-15 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210415_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='created_date',
            field=models.IntegerField(default=1618457578),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='update_date',
            field=models.IntegerField(default=1618457578),
        ),
    ]
