# Generated by Django 3.0 on 2021-04-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210415_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='created_date',
            field=models.IntegerField(default=1618481664),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='update_date',
            field=models.IntegerField(default=1618481664),
        ),
    ]
