# Generated by Django 3.0 on 2021-04-16 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210415_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='created_date',
            field=models.IntegerField(default=1618536197),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='update_date',
            field=models.IntegerField(default=1618536197),
        ),
    ]
