# Generated by Django 3.0 on 2021-04-16 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210416_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='created_date',
            field=models.IntegerField(default=1618545404),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='tax_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='update_date',
            field=models.IntegerField(default=1618545404),
        ),
    ]
