# Generated by Django 3.0 on 2021-05-04 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210416_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='country_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='district_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='province_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='ward_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='created_date',
            field=models.IntegerField(default=1620098266),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='update_date',
            field=models.IntegerField(default=1620098266),
        ),
    ]
