# Generated by Django 3.2 on 2021-04-14 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='currencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=250)),
                ('name', models.CharField(blank=True, max_length=250)),
                ('symbol', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso639_1', models.CharField(blank=True, max_length=250, null=True)),
                ('iso639_2', models.CharField(blank=True, max_length=250, null=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('nativeName', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='countrys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('code', models.CharField(blank=True, max_length=250, null=True)),
                ('callingCodes', models.CharField(blank=True, max_length=250, null=True)),
                ('capital', models.CharField(blank=True, max_length=250, null=True)),
                ('region', models.CharField(blank=True, max_length=250, null=True)),
                ('subregion', models.CharField(blank=True, max_length=250, null=True)),
                ('demonym', models.CharField(blank=True, max_length=250, null=True)),
                ('area', models.CharField(blank=True, max_length=250, null=True)),
                ('timezones', models.CharField(blank=True, max_length=250, null=True)),
                ('nativeName', models.CharField(blank=True, max_length=250, null=True)),
                ('numericCode', models.CharField(blank=True, max_length=250, null=True)),
                ('population', models.CharField(blank=True, max_length=250, null=True)),
                ('flag', models.CharField(blank=True, max_length=250, null=True)),
                ('currencies', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.currencies')),
                ('languages', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.languages')),
            ],
        ),
    ]
