# Generated by Django 3.2 on 2021-04-14 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrys',
            name='currencies',
        ),
        migrations.AddField(
            model_name='countrys',
            name='currencies',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='core.currencies'),
        ),
        migrations.RemoveField(
            model_name='countrys',
            name='languages',
        ),
        migrations.AddField(
            model_name='countrys',
            name='languages',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='core.languages'),
        ),
    ]
